version: "3.8"

services:
  fastapi_app:
    build: .
    ports:
      - "8002:8002"
    volumes:
      - .:/app
    depends_on:
      - accenture-db
    environment:
      - MONGO_URI=mongodb://root:example@accenture-db:27017/merger_search?authSource=admin
      - MONGO_DB_NAME=merger_search
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true

  accenture-db: 
    image: mongo:latest
    container_name: accenture-db
    restart: always
    ports:
      - "27020:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongo-data:
    driver: local
